// CSS
import './App.css'

// React
// import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { Navigate } from 'react-router-dom';

// Components
import Footer from "./Components/Footer/Footer";
import Navbar from './Components/Navbar/navbar';
import AllocationPage from "./Pages/AllocationPage";
import PiggyBank from "./Pages/PiggyBank"
import AccountsOverviewPage from "./Pages/accountsOverviewPage"
import Dashboard from './Pages/dashboard';
import SignedOutPage from './Components/SignedOutPage/SignedOutPage';
import { ProtectedRoute } from './Auth/Protected';

//Clerk
import { useAuth, SignedOut } from '@clerk/clerk-react';


function App() {
  // const [route, setRoute] = useState<string>("/")
  // console.log("You are in " + route)

  const { userId } = useAuth(); // Auto Generated By Clerk
  const userID = String(userId) 

  return (
  <Router>
    <Navbar/>
      <Routes>
        <Route path="*" element={<Navigate to="/" />} />
        <Route path="/" element={ <ProtectedRoute> <></> </ProtectedRoute>} />
        <Route path="/savings" element={ <PiggyBank/>} />
        <Route path="/dashboard" element={<ProtectedRoute> <Dashboard userID={userID}/> </ProtectedRoute>} />
        <Route path="/accounts" element={<ProtectedRoute> <AccountsOverviewPage user={userID}/> </ProtectedRoute>} />
        <Route path="/Allocations" element={<ProtectedRoute> <AllocationPage user={userID}/> </ProtectedRoute>} />
        <Route path="/expenses" element={<ProtectedRoute> <div>Expenses Page (Coming Soon)</div> </ProtectedRoute>} />
        <Route path="/reports" element={<ProtectedRoute> <div>Reports Page (Coming Soon)</div> </ProtectedRoute>} />
        <Route path="/login" element={<SignedOut> <SignedOutPage/> </SignedOut>}/>
    </Routes>
    <Footer/>
  </Router>
  )
}

export default App