// CSS
import './App.css'

// React
import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";

// Components
import Footer from "./Components/Footer/Footer";
import Navbar from './Components/Navbar/navbar';
import AllocationPage from "./Pages/AllocationPage";
import PiggyBank from "./Pages/PiggyBank"
import AccountsOverviewPage from "./Pages/accountsOverviewPage"
import Dashboard from './Pages/dashboard';

//Clerk
import { useAuth } from '@clerk/clerk-react';


function App() {
  const [route, setRoute] = useState<string>("/")
  console.log("You are in " + route)

  const { userId } = useAuth(); // Auto Generated By Clerk
  const userID = String(userId) 

  return (
    <Router>
      <Navbar/>
 
      <Routes>
        <Route path="/" element={ <> </> } />
        <Route path="/dashboard" element={<Dashboard userID={userID}/>} />
        <Route path="/savings" element={<PiggyBank />} />
        <Route path="/accounts" element={<AccountsOverviewPage setRoute={setRoute}/>} />
        <Route path="/Allocations" element={<AllocationPage user={userID}/>} />
        <Route path="/expenses" element={<div>Expenses Page (Coming Soon)</div>} />
        <Route path="/reports" element={<div>Reports Page (Coming Soon)</div>} />
      </Routes>
      
      <Footer/>
    </Router>
  )
}

export default App